export default {
  objectID: "sdfdsf",
  isHighlight: false,
  accessionNumber: "2012.441.3",
  accessionYear: "2012",
  isPublicDomain: false,
  primaryImage: "https://source.unsplash.com/random/800X600",
  primaryImageSmall: "",
  additionalImages: "[]",
  constituents: null,
  department: "The Michasdfel",
  objectName: "Shoulder cloth",
  title: "Man's shoulder cloth (Salendang)",
  culture: "Minangkabau people",
  period: "",
  dynasty: "",
  reign: "",
  portfolio: "",
  artistRole: "",
  artistPrefix: "",
  artistDisplayName: "",
  artistDisplayBio: "",
  artistSuffix: "",
  artistAlphaSort: "",
  artistNationality: "",
  artistBeginDate: "",
  artistEndDate: "",
  artistGender: "",
  artistWikidata_URL: "",
  artistULAN_URL: "",
  objectDate: "Mid- to late 19th century",
  objectBeginDate: 1850,
  objectEndDate: 1900,
  medium: "Cotton",
  dimensions: "L. 118 x W. 19 in. (299.72 x 48.26 cm)",
  measurements: "[{…}]",
  creditLine: "Gift of John Summerfield, in memory of Anne Summerfield, 2012",
  geographyType: "",
  city: "",
  state: "West Sumatra",
  county: "",
  country: "Indonesia",
  region: "",
  subregion: "",
  locale: "",
  locus: "",
  excavation: "",
  river: "",
  classification: "Textiles-Woven",
  rightsAndReproduction: "",
  linkResource: "",
  metadataDate: "2020-03-02T21:50:01.377Z",
  repository: "Metropolitan Museum of Art, New York, NY",
  objectURL: "https://www.metmuseum.org/art/collection/search/321245",
  tags: null,
  objectWikidata_URL: "",
  isTimelineWork: false,
  GalleryNumber: ""
};
